image node:12

cache:
  key: $CI_COMMIT_REF_SLUG
  paths: 
    - node_modules/

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hardcore-shirley-684888.netlify.app
  only:
    - master
  script:
    - npm install
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod