image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

test_async:
  script:
  - node ./specs/start.js ./specs/async.spec.js

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hardcore-shirley-684888.netlify.app
  only:
    - master
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod