image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths: 
    - node_modules/

stages:
  - deploy

npm_install:
  stage: build
  image: node:12
  script:
    - npm install
  artifacts:
    paths: 
      - node_modules/

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hardcore-shirley-684888.netlify.app
  only:
    - master
  script:
    - node ./specs/start.js ./specs/async.spec.js
    - npm i
    # your build command
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod