image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hardcore-shirley-684888.netlify.app
  only:
    - master
  script:
    - npm i
    # your build command
    - npx eleventy
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod